# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "mpt3sas" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "nct6775" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/NIXOS";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/HOME";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "zroot/HOME/root";
      fsType = "zfs";
    };

  fileSystems."/srv/private" =
    { device = "zdata/PRIVATE";
      fsType = "zfs";
    };

  fileSystems."/srv/public" =
    { device = "zdata/PUBLIC";
      fsType = "zfs";
    };

  fileSystems."/srv/public/media" =
    { device = "zdata/PUBLIC/MEDIA";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/077D-C139";
      fsType = "vfat";
    };

  swapDevices = [ ];
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
